// Copyright (c) 2026 Andreas Huelsmann. Licensed under MIT. See LICENSE and README.md for details.
namespace Moba.Sound;

using System.Buffers.Binary;

/// <summary>
/// Removes a sustained low-level tail from PCM WAV files generated by speech engines.
/// </summary>
public static class PcmWavePostProcessor
{
    private const int MinimumTrailingNoiseMilliseconds = 40;
    private const int PreservedTailMilliseconds = 30;
    private const int FadeOutMilliseconds = 15;
    private const short NoiseThreshold = 500;

    /// <summary>
    /// Examines a WAV file and removes a trailing low-level signal when it is long enough to be audible.
    /// </summary>
    public static PcmWavePostProcessResult Process(string wavPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(wavPath);

        var wavBytes = File.ReadAllBytes(wavPath);
        if (!TryReadPcm16Wave(wavBytes, out var wave))
        {
            return PcmWavePostProcessResult.Unsupported;
        }

        var frameCount = wave.DataLength / wave.BlockAlign;
        var lastSignificantFrame = FindLastSignificantFrame(wavBytes, wave, frameCount);
        if (lastSignificantFrame < 0)
        {
            return new PcmWavePostProcessResult(false, wave.SampleRate, wave.Channels, 0, 0);
        }

        var preservedFrames = MillisecondsToFrames(PreservedTailMilliseconds, wave.SampleRate);
        var retainedFrameCount = Math.Min(frameCount, lastSignificantFrame + 1 + preservedFrames);
        var trimmedFrameCount = frameCount - retainedFrameCount;
        if (trimmedFrameCount < MillisecondsToFrames(MinimumTrailingNoiseMilliseconds, wave.SampleRate))
        {
            return new PcmWavePostProcessResult(false, wave.SampleRate, wave.Channels, 0, CalculateTailPeak(wavBytes, wave));
        }

        ApplyFadeOut(wavBytes, wave, retainedFrameCount);
        var retainedDataLength = retainedFrameCount * wave.BlockAlign;
        var processedBytes = wavBytes[..(wave.DataOffset + retainedDataLength)];
        BinaryPrimitives.WriteInt32LittleEndian(processedBytes.AsSpan(4, 4), processedBytes.Length - 8);
        BinaryPrimitives.WriteInt32LittleEndian(processedBytes.AsSpan(wave.DataLengthOffset, 4), retainedDataLength);
        File.WriteAllBytes(wavPath, processedBytes);

        return new PcmWavePostProcessResult(
            true,
            wave.SampleRate,
            wave.Channels,
            trimmedFrameCount,
            CalculateTailPeak(wavBytes, wave));
    }

    private static bool TryReadPcm16Wave(byte[] wavBytes, out PcmWaveInfo wave)
    {
        wave = default;
        if (wavBytes.Length < 12 || !wavBytes.AsSpan(0, 4).SequenceEqual("RIFF"u8) || !wavBytes.AsSpan(8, 4).SequenceEqual("WAVE"u8))
        {
            return false;
        }

        var offset = 12;
        var formatFound = false;
        while (offset + 8 <= wavBytes.Length)
        {
            var chunkId = wavBytes.AsSpan(offset, 4);
            var chunkLength = BinaryPrimitives.ReadInt32LittleEndian(wavBytes.AsSpan(offset + 4, 4));
            var chunkDataOffset = offset + 8;
            if (chunkLength < 0 || chunkDataOffset + chunkLength > wavBytes.Length)
            {
                return false;
            }

            if (chunkId.SequenceEqual("fmt "u8) && chunkLength >= 16)
            {
                var audioFormat = BinaryPrimitives.ReadInt16LittleEndian(wavBytes.AsSpan(chunkDataOffset, 2));
                var channels = BinaryPrimitives.ReadInt16LittleEndian(wavBytes.AsSpan(chunkDataOffset + 2, 2));
                var sampleRate = BinaryPrimitives.ReadInt32LittleEndian(wavBytes.AsSpan(chunkDataOffset + 4, 4));
                var blockAlign = BinaryPrimitives.ReadInt16LittleEndian(wavBytes.AsSpan(chunkDataOffset + 12, 2));
                var bitsPerSample = BinaryPrimitives.ReadInt16LittleEndian(wavBytes.AsSpan(chunkDataOffset + 14, 2));
                if (audioFormat != 1 || channels is < 1 or > 2 || sampleRate <= 0 || bitsPerSample != 16 || blockAlign != channels * sizeof(short))
                {
                    return false;
                }

                wave = new PcmWaveInfo(sampleRate, channels, blockAlign, 0, 0, 0);
                formatFound = true;
            }
            else if (chunkId.SequenceEqual("data"u8) && formatFound && chunkDataOffset + chunkLength == wavBytes.Length)
            {
                wave = wave with { DataOffset = chunkDataOffset, DataLengthOffset = offset + 4, DataLength = chunkLength };
                return chunkLength % wave.BlockAlign == 0;
            }

            offset = chunkDataOffset + chunkLength + (chunkLength & 1);
        }

        return false;
    }

    private static int FindLastSignificantFrame(byte[] wavBytes, PcmWaveInfo wave, int frameCount)
    {
        for (var frameIndex = frameCount - 1; frameIndex >= 0; frameIndex--)
        {
            var frameOffset = wave.DataOffset + (frameIndex * wave.BlockAlign);
            for (var channel = 0; channel < wave.Channels; channel++)
            {
                var sample = BinaryPrimitives.ReadInt16LittleEndian(wavBytes.AsSpan(frameOffset + (channel * sizeof(short)), sizeof(short)));
                if (Math.Abs((int)sample) > NoiseThreshold)
                {
                    return frameIndex;
                }
            }
        }

        return -1;
    }

    private static int CalculateTailPeak(byte[] wavBytes, PcmWaveInfo wave)
    {
        var frameCount = wave.DataLength / wave.BlockAlign;
        var tailFrames = Math.Min(frameCount, MillisecondsToFrames(100, wave.SampleRate));
        var peak = 0;
        for (var frameIndex = frameCount - tailFrames; frameIndex < frameCount; frameIndex++)
        {
            var frameOffset = wave.DataOffset + (frameIndex * wave.BlockAlign);
            for (var channel = 0; channel < wave.Channels; channel++)
            {
                var sample = BinaryPrimitives.ReadInt16LittleEndian(wavBytes.AsSpan(frameOffset + (channel * sizeof(short)), sizeof(short)));
                peak = Math.Max(peak, Math.Abs((int)sample));
            }
        }

        return peak;
    }

    private static void ApplyFadeOut(byte[] wavBytes, PcmWaveInfo wave, int retainedFrameCount)
    {
        var fadeFrameCount = Math.Min(retainedFrameCount, MillisecondsToFrames(FadeOutMilliseconds, wave.SampleRate));
        for (var fadeFrameIndex = 0; fadeFrameIndex < fadeFrameCount; fadeFrameIndex++)
        {
            var frameIndex = retainedFrameCount - fadeFrameCount + fadeFrameIndex;
            var multiplier = (double)(fadeFrameCount - fadeFrameIndex - 1) / fadeFrameCount;
            var frameOffset = wave.DataOffset + (frameIndex * wave.BlockAlign);
            for (var channel = 0; channel < wave.Channels; channel++)
            {
                var sampleOffset = frameOffset + (channel * sizeof(short));
                var sample = BinaryPrimitives.ReadInt16LittleEndian(wavBytes.AsSpan(sampleOffset, sizeof(short)));
                BinaryPrimitives.WriteInt16LittleEndian(wavBytes.AsSpan(sampleOffset, sizeof(short)), (short)Math.Round(sample * multiplier));
            }
        }
    }

    private static int MillisecondsToFrames(int milliseconds, int sampleRate) =>
        Math.Max(1, (int)Math.Ceiling(sampleRate * (milliseconds / 1000d)));

    private readonly record struct PcmWaveInfo(int SampleRate, int Channels, int BlockAlign, int DataOffset, int DataLengthOffset, int DataLength);
}

/// <summary>
/// Outcome of PCM WAV tail processing.
/// </summary>
public readonly record struct PcmWavePostProcessResult(bool WasProcessed, int SampleRate, int Channels, int TrimmedFrameCount, int TailPeak)
{
    /// <summary>
    /// Indicates that the WAV file was not a supported PCM 16-bit file.
    /// </summary>
    public static PcmWavePostProcessResult Unsupported => new(false, 0, 0, 0, 0);
}
