<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Labs.WinUI.Controls.DataTable" Version="0.1.251217-build.2433" />
    <PackageVersion Include="CommunityToolkit.Labs.WinUI.Controls.Ribbon" Version="0.1.251217-build.2433" />
    <PackageVersion Include="CommunityToolkit.WinUI.Animations" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Collections" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.HeaderedControls" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.LayoutTransformControl" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.RangeSelector" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.TabbedCommandBar" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.DeveloperTools" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Helpers" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Media" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Triggers" Version="8.2.251219" />
    <PackageVersion Include="Docnet.Core" Version="2.6.0" />
    <PackageVersion Include="GitHub.Copilot.SDK" Version="0.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="8.5.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Azure.AI.Vision.ImageAnalysis" Version="1.0.0" />
    <PackageVersion Include="Microsoft.CognitiveServices.Speech" Version="1.48.2" />
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="System.Speech" Version="10.0.5" />
    <PackageVersion Include="System.Windows.Extensions" Version="10.0.5" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="CommunityToolkit.Maui" Version="14.0.1" />
    <PackageVersion Include="CommunityToolkit.Maui.MediaElement" Version="8.0.1" />
    <PackageVersion Include="UraniumUI.Material" Version="2.15.0" />
    <PackageVersion Include="UraniumUI.Icons.MaterialIcons" Version="2.15.0" />
    <PackageVersion Include="Xamarin.AndroidX.Startup.StartupRuntime" Version="1.2.0.7" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4654" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools.MSIX" Version="1.7.251221100" />
    <PackageVersion Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
    <PackageVersion Include="Microsoft.SourceLink.AzureRepos.Git" Version="10.0.201" />
    <PackageVersion Include="coverlet.collector" Version="8.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageVersion Include="NUnit" Version="4.5.1" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.12.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.51" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="CommunityToolkit.WinUI.UI.Controls.Markdown" Version="7.1.2" />
  </ItemGroup>
</Project>