// Copyright (c) 2025-2026 Andreas Huelsmann. Licensed under MIT. See LICENSE and README.md for details.
namespace Moba.SharedUI.ViewModel;

using CommunityToolkit.Mvvm.ComponentModel;
using Domain.TrackPlan;
using Domain.Geometry;

/// <summary>
/// ViewModel for a track segment in the topology-based track plan.
/// Position and PathData are computed by the TrackLayoutRenderer, not stored.
/// </summary>
public partial class TrackSegmentViewModel : ObservableObject
{
    private readonly TrackSegment _segment;

    public TrackSegmentViewModel(TrackSegment segment)
    {
        ArgumentNullException.ThrowIfNull(segment);
        _segment = segment;
    }

    /// <summary>
    /// Access to underlying domain model.
    /// </summary>
    public TrackSegment Model => _segment;



    #region Domain Properties (from TrackSegment)

    public string Id => _segment.Id;
    public string ArticleCode => _segment.ArticleCode;
    public string? Name => _segment.Name;
    public string? Layer => _segment.Layer;

    /// <summary>
    /// Assigned feedback sensor port (InPort 1-2048).
    /// </summary>
    public uint? AssignedInPort
    {
        get => _segment.AssignedInPort;
        set
        {
            if (_segment.AssignedInPort != value)
            {
                _segment.AssignedInPort = value;
                OnPropertyChanged();
                OnPropertyChanged(nameof(HasInPort));
                OnPropertyChanged(nameof(InPortDisplayText));
            }
        }
    }

    public bool HasInPort => _segment.AssignedInPort.HasValue;
    public string InPortDisplayText => _segment.AssignedInPort?.ToString() ?? "";

    /// <summary>
    /// Whether this segment is currently occupied (train on segment).
    /// Proxies to Model.IsOccupied (set by FeedbackStateManager).
    /// </summary>
    public bool IsOccupied => _segment.IsOccupied;

    #endregion

    #region Render Properties (proxy to Model.WorldTransform)

    /// <summary>
    /// World transformation matrix (calculated by TopologyRenderer at runtime).
    /// Pure topology-first: Proxies to Model.WorldTransform (NOT stored in ViewModel).
    /// </summary>
    public Transform2D WorldTransform
    {
        get => _segment.WorldTransform;
        set
        {
            if (_segment.WorldTransform != value)
            {
                _segment.WorldTransform = value;
                OnPropertyChanged();
                OnPropertyChanged(nameof(LabelX));
                OnPropertyChanged(nameof(LabelY));
                OnPropertyChanged(nameof(InPortLabelY));
            }
        }
    }

    /// <summary>
    /// SVG path data (generated by renderer from TrackGeometryLibrary).
    /// Local coordinates - transformation applied via WorldTransform.
    /// </summary>
    [ObservableProperty]
    private string? pathData = "M 0,0";

    #endregion


    #region UI State

    /// <summary>
    /// Whether this segment is currently selected.
    /// </summary>
    [ObservableProperty]
    private bool isSelected;

    /// <summary>
    /// Whether this segment is currently triggered (feedback active).
    /// </summary>
    [ObservableProperty]
    private bool isTriggered;

    /// <summary>
    /// Whether this segment is being dragged.
    /// </summary>
    [ObservableProperty]
    private bool isDragging;

    /// <summary>
    /// Whether this segment is part of a group being dragged.
    /// </summary>
    [ObservableProperty]
    private bool isPartOfDragGroup;

    /// <summary>
    /// Whether this segment is a potential snap target during drag.
    /// </summary>
    [ObservableProperty]
    private bool isSnapTarget;

    #endregion

    #region Drag Support

    /// <summary>
    /// Offset X from segment origin to drag start point.
    /// Used to maintain relative position during drag.
    /// </summary>
    public double DragOffsetX { get; set; }

    /// <summary>
    /// Offset Y from segment origin to drag start point.
    /// </summary>
    public double DragOffsetY { get; set; }

    /// <summary>
    /// Move segment by delta (for group drag).
    /// DISABLED in pure topology-first architecture - drag modifies connections, not coordinates.
    /// TODO: Implement topology-based drag (snap to connectors, create new connections).
    /// </summary>
    public void MoveBy(double deltaX, double deltaY)
    {
        _ = deltaX;
        _ = deltaY;
        // Pure topology-first: No coordinate manipulation
        // Dragging should create/modify connections, then trigger re-render
        // For now: disabled until snap logic is implemented
    }

    #endregion


    #region Computed Properties for UI

    /// <summary>
    /// Label X position (center of segment).
    /// </summary>
    public double LabelX => WorldTransform.TranslateX - 10;

    /// <summary>
    /// Label Y position (center of segment).
    /// </summary>
    public double LabelY => WorldTransform.TranslateY - 6;

    /// <summary>
    /// InPort label Y position.
    /// </summary>
    public double InPortLabelY => LabelY - 14;

    #endregion


}
