<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Moba.Display</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Drawing.Common" />
    </ItemGroup>
</Project>